matrix:
  include:
    - language: python
      python: 3.5
      before_script:
        - cd gateway
      install:
        - pip install requests serial pylint
      script:
        - pylint gateway.py

    - language: node_js
      node_js:
        - "node"
        - "8"
      before_install:
        - "echo $PWD"
        - "echo $HOME"
        - "ls $PWD"
        - cd server
      before_script:
        - cd server
      install:
        - "echo $PWD"
        - npm install
      script:
        - "echo $PWD"
        - npm run test
notifications:
  email:
    - saku.rautiainen@iki.fi