matrix:
  include:
    - language: python
      python: 3.5
      install:
        - pip install requests serial pylint
      script:
        - pylint gateway/gateway.py

    - language: node_js
      node_js:
        - "node"
        - "8"
      script:

notifications:
  email:
    - saku.rautiainen@iki.fi